### ISSUE TITLE
Updates to SourceForge XeTeX

### ISSUE THREAD

**Issue by spl** [tectonic-typesetting/tectonic-staging#8]
This issue is just to inform you that I noticed updates to the [SourceForge XeTeX repository](https://sourceforge.net/p/xetex/) ([recent history](https://sourceforge.net/p/xetex/code/ci/8af2b58c82bdfcd2791a31b506c602d6b9abdf1c/log/)). It appears the authors have started working on XeTeX again.

**Comment by pkgw** [comment]
Thanks for the notice! If you are feeling very adventurous you could attempt to follow [the instructions in the README](https://github.com/tectonic-typesetting/tectonic-staging#updating-the-reference-source-code) to update the reference code here to track upstream, but it's far from an automatic process so it would take a lot of time to figure everything out.

**Comment by spl** [comment]
Am I correct in understanding that the only upstream that you currently track is the TeX Live repository? I didn't checked if TeX Live brought over any of the XeTeX changes. Plus, cloning that Git repository is a bit daunting for me: I have limited data for a month, and I don't want to use it all up. 😉 Possibly a shallow clone would work, but I haven't tried it.

**Comment by pkgw** [comment]
Yes, that's right. That isn't a rigorously-motivated policy, but I think there have been a few cases where TeXLive has gotten fixes before the SourceForge version. But given that that's how things have been, I would like to stick with using one upstream repo if possible and not both, to be able to rigorously point to exactly what "upstream" is.

It does look like TeXLive has pulled in the Git changes:

https://tug.org/svn/texlive/trunk/Build/source/texk/web2c/xetexdir/ 

It would be good to have some notes in the README about options to save bandwidth! I believe a shallow clone would save a lot since a lot of the repo size is executables churning with every rebuild (sigh), but this isn't something I've investigated yet.

**Comment by spl** [comment]
> That isn't a rigorously-motivated policy, but I think there have been a few cases where TeXLive has gotten fixes before the SourceForge version. But given that that's how things have been, I would like to stick with using one upstream repo if possible and not both, to be able to rigorously point to exactly what "upstream" is.

Sure, absolutely.

> I believe a shallow clone would save a lot since a lot of the repo size is executables churning with every rebuild (sigh), but this isn't something I've investigated yet.

If it's not too much effort, would you mind doing a shallow clone (`git clone --depth 1`) of the TeX Live repository and telling me how much disk space the new directory takes up? I believe you can even do a clone of your own local repository, and that should be faster than a clone of the remote.

**Comment by pkgw** [comment]
If I do a shallow clone, the `.git` directory of the resulting repo is 4.2 GiB. The whole checkout directory (including `.git`) is 13 GiB. I *think* that means that basically it's 4.2 GiB of data transfer and than ~9 GiB of uncompressing files, but I'm not 100% sure that's how to account for it.

**Comment by spl** [comment]
@pkgw Thanks for doing that. It's still a lot, but it's better than the whole thing. Maybe if I end up with enough extra data at the end of the month (and remember to do it), I'll try a checkout.

**Comment by pkgw** [comment]
@spl Friend with fast internet at work + a USB stick, or something?

**Comment by spl** [comment]
Unfortunately, I don't have those git-knowledgeable connections. But maybe one day I can get my wife's laptop set up to do it and ask her to hit <Enter> when she gets to work. We'll see. 😏

**Comment by ratmice** [comment]
I don't see any of this reflected on the TeX-Live website yet, but apparently there is a copy of 
the source repository, there is also a copy of the synchronization scripts, the source repo comes in at 1.1G, 
https://github.com/TeX-Live/texlive-source
https://github.com/TeX-Live/sync-scripts

It'd be really nice if we could build tectonic_bundle_git_config, to run with the sync scripts, for the bundle? I still haven't managed to digest the whole process.

**Comment by pkgw** [comment]
Well, it has been a little while, but I think we are going to need to confront this.

In digging into tectonic-typesetting/tectonic#478, I noticed a difference between `xelatex` and Tectonic at the beginning of the processing of a simple document. Tectonic prints:

```
(test3.tex
LaTeX2e <2018-04-01> patch level 4
Babel <3.20> and hyphenation patterns for 84 language(s) loaded.
```

But `xelatex` prints:

```
(test3.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06>
```

It looks like when we generate the format file, the expl3 stuff is not getting loaded:

```
UTF-8 Welsh hyphenation patterns (hyph-cy.tex))) (ltexpl.ltx
Skipping expl3-dependent extensions)
 ) )
```

That, in turn, is because we don't define a `\filesize` primitive or something related.

I think this means that we need to bite the bullet and catch up to recent XeTeX developments. I was kind of hoping that we could get the TeXLive 2020 update out without having to tackle this, but with such a fundamental difference between us and XeTeX, I think it would be a very bad idea to ignore it.

**Comment by pkgw** [comment]
On the plus side, I have split the bundle-creation framework into a new [tectonic-texlive-bundles](https://github.com/tectonic-typesetting/tectonic-texlive-bundles) repo, which means that I should be able to streamline this repo a bit too. It might be a good time to look into whether I can use some of the streamlining approaches mentioned above.

**Comment by pkgw** [comment]
Before I forget: it looks like the expl3 stuff tests the OS platform by probing `/dev/null`. We might need to special-case that in the I/O layer to get everything to work happily.

**Comment by pkgw** [comment]
I've been working on this. The pull request tectonic-typesetting/tectonic#666 will contain this catchup effort. It's still a work in progress.

**Comment by pkgw** [comment]
Never updated this issue, but this work is done!
